/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.controller.LoginController', {
    extend: 'Ext.app.Controller',

    views: [
        'MainViewport',
        'MainContainer'
    ],

    init: function(application) {
        this.control({
            'form[itemId=loginForm] button[itemId=loginBtn]': {
                click: this.doLogin
            },
            'form[itemId=loginForm] button[itemId=QueryBtn]': {
                click: this.showQueryWin
            },
            'form[itemId=loginForm] button[itemId=resetBtn]': {
                click: this.doReset
            }
        });
    },

    doLogin: function(btn, e, eOpts) {
        var form = btn.up('form').getForm();
        if (form.isValid()) {
            form.submit({
                success: this.loginSuccess,
                failure: this.loginFailed
            });
        }
        else {
            Ext.Msg.alert('無法登入', '請檢查表單資料！');
        }
    },

    loginSuccess: function(form, action) {
        var mainVP = Ext.getCmp('mainVP');
        mainVP.removeAll();
        mainVP.add({xtype: 'maincontainer'});

        //登入後顯示使用者名稱
        //Ext.get('username').update(action.result.username, false);
        Ext.get('username').update(action.result.fullName+"("+action.result.username+")", false);

        //計時檢查連線
        Utilities.checkSession();
    },

    loginFailed: function() {
        Ext.Msg.alert('無法登入', '無法通過驗證！');
    },

    showQueryWin: function() {

    },

    doReset: function(btn, e, eOpts) {
        console.log('doReset');
        var form = btn.up('form').getForm();
        form.reset();
    }

});
