/*
 * File: app/view/CommonSaveBtn.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.view.CommonSaveBtn', {
    extend: 'Ext.button.Button',
    alias: 'widget.commonsavebtn',

    requires: [
        'foodpark.view.CommonSaveBtnViewModel'
    ],

    viewModel: {
        type: 'commonsavebtn'
    },
    itemId: 'commonSaveBtn',
    style: 'font-family:Pictos;',
    glyph: 86,
    text: 'Save',

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processCommonSaveBtn(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processCommonSaveBtn: function(config) {
        config.text=Utilities.getMsg('common.saveBtn.label');

        return config;
    }

});