/*
 * File: app/view/CommonShowToolbar.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.view.CommonShowToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.commonshowtoolbar',

    requires: [
        'foodpark.view.CommonShowToolbarViewModel',
        'foodpark.view.CommonSaveBtn',
        'foodpark.view.CommonDeleteBtn',
        'foodpark.view.CommonCancelBtn',
        'foodpark.view.CommonPrintBtn',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'commonshowtoolbar'
    },
    itemId: 'commonShowToolbar',

    items: [
        {
            xtype: 'commonsavebtn'
        },
        {
            xtype: 'commondeletebtn'
        },
        {
            xtype: 'commoncancelbtn'
        },
        {
            xtype: 'commonprintbtn',
            hidden: true
        }
    ]

});