/*
 * File: app/view/LoginContainer.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.view.LoginContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.logincontainer',

    requires: [
        'foodpark.view.LoginContainerViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'logincontainer'
    },
    frame: true,
    id: 'login',
    minHeight: 300,
    defaults: {
        anchor: '100%'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 3,
            itemId: 'header',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    height: 200,
                    itemId: 'main',
                    scrollable: true,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'form',
                            reference: 'mainForm',
                            frame: true,
                            itemId: 'loginForm',
                            layout: 'auto',
                            bodyPadding: 10,
                            url: 'j_spring_security_check',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'logo'
                                },
                                {
                                    xtype: 'container',
                                    frame: true,
                                    itemId: 'login-box',
                                    items: [
                                        {
                                            xtype: 'container',
                                            itemId: 'top'
                                        },
                                        {
                                            xtype: 'container',
                                            html: 'Welcome to The Foodpark Manage System.',
                                            itemId: 'info'
                                        },
                                        {
                                            xtype: 'container',
                                            itemId: 'login-input',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: '帳號 / username',
                                                    name: 'j_username',
                                                    inputId: 'system_user'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: '密碼 / password',
                                                    name: 'j_password',
                                                    inputId: 'system_pass',
                                                    inputType: 'password'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            itemId: 'remember',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: '記住密碼 / Remember me'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 50,
                                            itemId: 'bottom-bar',
                                            layout: 'absolute',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    x: 180,
                                                    y: 10,
                                                    itemId: 'buttons',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'resetBtn',
                                                            margin: 2,
                                                            text: '重設'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            hidden: true,
                                                            itemId: 'registerBtn',
                                                            margin: 2,
                                                            text: '註冊'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'loginBtn',
                                                            margin: 2,
                                                            text: '登入'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    html: '<div align="center"> 版權所有 © 2016 Agricloud. All Rights   Reserved. CopyRight<br>\n    本系統由雲端農場研發設計 version web1.0\n </div>',
                    itemId: 'copyright',
                    style: {
                        align: 'center'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            height: 81,
            html: '<footer>\n <div align="right"> ．擁有產品履歷．安全．信賴．e化管理 </div> \n </footer>',
            itemId: 'footer'
        }
    ]

});