/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'foodpark.view.MainViewportViewModel',
        'foodpark.view.MainViewportViewController',
        'foodpark.view.LoginContainer',
        'Ext.container.Container'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    id: 'mainVP',
    layout: 'card',

    items: [
        {
            xtype: 'logincontainer'
        }
    ],
    listeners: {
        afterrender: 'onMainVPAfterRender'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processMainViewport(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processMainViewport: function(config) {
        Utilities.readSysConfig();
    }

});