/*
 * File: app/view/MainContainerViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodpark.view.MainContainerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.maincontainer',

    addView: function(xtypeStr, tabName, docLink) {
        var mainPanel = this.lookupReference('mainPanel');

        //console.log(mainPanel);

        mainPanel.removeAll();

        mainPanel.add({
            xtype: xtypeStr,
            title:tabName// +'　'+'<a href="'+docLink+'" target="_blank" style="color:grey;text-decoration:underline;">說明</a>'
        });
    },

    onSiteMaintainClick: function(button, e, eOpts) {
        var xtypeStr = 'siteview';
        var tabName = Utilities.getMsg('mainContainer.siteMaintain.label');//'農場維護';
        var docLink = '';//'https://drive.google.com/file/d/0B_Z9et2ajnisQ2F1RkV6aTZQSTA/edit?usp=sharing';
        this.addView(xtypeStr,tabName,docLink);
    },

    onButtonClick: function(button, e, eOpts) {
        Utilities.logout();
    }

});
